[package]
name = "rustc-rayon-core"
version = "1.3.0" # reminder to update html_root_url attribute
authors = ["Niko Matsakis <niko@alum.mit.edu>",
           "Josh Stone <cuviper@gmail.com>"]
description = "Core APIs for Rayon"
license = "Apache-2.0/MIT"
repository = "https://github.com/rayon-rs/rayon"
documentation = "https://docs.rs/rayon/"
links = "rayon-core"
build = "build.rs"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]

[dependencies]
rand = "0.3"
num_cpus = "1.2"
coco = "0.3.2"
libc = "0.2.16"
lazy_static = "1"
context = { git = "https://github.com/Zoxc/context-rs.git" }
scoped-tls = { git = "https://github.com/Zoxc/scoped-tls.git", features=["nightly"] }
crossbeam-channel = "0.1"
ctrlc = { version = "3.0.3", optional = true }

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2.8"

[dependencies.parking_lot]
version = "0.5"
features = ["nightly"]

[build-dependencies]
gcc = "0.3.10"

[features]
default = ["tlv"]
debug = ["ctrlc"]
tlv = []

[dev-dependencies]
