environment:
  RUST_MIN_STACK: 16777216
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      RUSTFLAGS: --cfg rayon_unstable

    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      RUSTFLAGS: --cfg rayon_unstable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

matrix:
  fast_finish: true

build: false

test_script:
  - cargo build
  - cargo test -p rayon
  - cargo test -p rayon-core

branches:
  only:
    - master
    - staging
    - trying
