[package]
name = "rayon"
version = "0.6.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
description = "Simple work-stealing parallelism for Rust"
license = "Apache-2.0/MIT"
repository = "https://github.com/nikomatsakis/rayon"
documentation = "https://docs.rs/rayon/"

[dependencies]
rand = "0.3"
num_cpus = "1.2"
deque = "0.3.1"
libc = "0.2.16"
lazy_static = "0.2.2"
futures = { version = "0.1.7", optional = true }

[dev-dependencies]
compiletest_rs = "0.2.1"
docopt = "0.6"
num = "0.1.30"
rustc-serialize = "0.3"

[features]
# Unstable APIs that have not yet
# proven their utility.
unstable = ["futures"]
