[package]
name = "rayon"
version = "0.4.2"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
description = "Simple work-stealing parallelism for Rust"
license = "Apache-2.0/MIT"
repository = "https://github.com/nikomatsakis/rayon"
documentation = "https://docs.rs/rayon/"

[dependencies]
rand = "0.3"
num_cpus = "1.0"
deque = "0.3.1"

[dev-dependencies]
compiletest_rs = "0.2.1"
num = "0.1.30"

[features]
nightly = []

# Unstable APIs that have not yet
# proven their utility.
unstable = []
