[package]
name = "rayon"
# Reminder to update html_rool_url in lib.rs when updating version
version = "0.9.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>",
           "Josh Stone <cuviper@gmail.com>"]
description = "Simple work-stealing parallelism for Rust"
license = "Apache-2.0/MIT"
repository = "https://github.com/rayon-rs/rayon"
documentation = "https://docs.rs/rayon/"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]

[workspace]
members = ["rayon-demo", "rayon-core", "rayon-futures"]
exclude = ["ci"]

[dependencies]
rayon-core = { version = "1.3", path = "rayon-core" }

# This is a public dependency!
[dependencies.either]
version = "1.0"
default-features = false

[dev-dependencies]
compiletest_rs = "0.3"
docopt = "0.8"
lazy_static = "1"
rand = "0.3"
serde = "1"
serde_derive = "1"
