[package]
name = "rayon"
# Reminder to update html_rool_url in lib.rs when updating version
version = "1.0.1"
authors = ["Niko Matsakis <niko@alum.mit.edu>",
           "Josh Stone <cuviper@gmail.com>"]
description = "Simple work-stealing parallelism for Rust"
license = "Apache-2.0/MIT"
repository = "https://github.com/rayon-rs/rayon"
documentation = "https://docs.rs/rayon/"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]

[workspace]
members = ["rayon-demo", "rayon-core", "rayon-futures"]
exclude = ["ci"]

[dependencies]
rayon-core = { version = "1.4", path = "rayon-core" }

# This is a public dependency!
[dependencies.either]
version = "1.0"
default-features = false

[dev-dependencies]
docopt = "0.8"
lazy_static = "1"
rand = "0.4"
serde = "1"
serde_derive = "1"

# mingw linking rustc crates is missing -ldbghelp, rust-lang/rust#47359
[target.'cfg(not(all(windows, target_env = "gnu")))'.dev-dependencies]
compiletest_rs = "0.3"
