[package]
name = "rayon-demo"
version = "0.0.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
publish = false

[dependencies]
rayon = { path = "../" }
cgmath = "0.16"
docopt = "0.8"
fixedbitset = "0.1.5"
glium = "0.20"
lazy_static = "1"
odds = "0.3"
rand = "0.4"
regex = "0.2"
serde = "1"
serde_derive = "1"
time = "0.1"

[dev-dependencies]
num = "0.1.30"
