[package]
name = "rayon-demo"
version = "0.0.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
publish = false

[dependencies]
rayon = { path = "../" }
cgmath = "0.17"
docopt = "1"
fixedbitset = "0.2.0"
glium = "0.25.1"
lazy_static = "1"
odds = "0.3"
rand = "0.6"
rand_xorshift = "0.1"
regex = "1"
serde = "1"
serde_derive = "1"
time = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }

[dev-dependencies]
num = "0.2"
