[package]
name = "rayon-demo"
version = "0.0.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
publish = false

[dependencies]
rayon = { path = "../" }
cgmath = "0.16"
docopt = "1"
fixedbitset = "0.1.5"
glium = "0.21"
lazy_static = "1"
libc = "0.2"
odds = "0.3"
rand = "0.5"
regex = "1"
serde = "1"
serde_derive = "1"
time = "0.1"
winapi = { version = "0.3", features = ["processthreadsapi"] }

[dev-dependencies]
num = "0.2"
