[package]
name = "rayon-demo"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
rayon = { path = "../", features = ["unstable"] }
cgmath = "0.11"
docopt = "0.6"
glium = "0.15"
rand = "0.3"
rustc-serialize = "0.3"
time = "0.1"
itertools = "0.4"
num = "0.1.30"
lazy_static = "0.2.1"
fixedbitset = "0.1.5"
regex = "0.1.80"